# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  - 5.4
  - 5.5
  - 5.6

# optionally specify a list of environments, for example to test different RDBMS
#env:
#  - DB=mysql
#  - DB=pgsql

sudo: required

services:
  - docker

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - mv application/config/database.ci.php application/config/database.php
  - git clone https://github.com/EASOL/easol-docker.git
  - cd easol-docker
  # Use the current build as the target site
  - sed -i -e "s|./easol-app:/usr/share/nginx/html|$TRAVIS_BUILD_DIR:/usr/share/nginx/html|" "docker-compose.yml"

# omitting "script:" will default to phpunit
script:
  - docker-compose build
  - docker-compose up -d
  - docker ps -a
  - docker-compose run php sh -c "cd /usr/share/nginx/html && vendor/bin/phpunit -c application/tests/phpunit.xml"

after_script:
  - docker-compose stop
  - docker-compose rm -f

# configure notifications (email, IRC, campfire etc)
#notifications:
#  irc: "irc.freenode.org#travis"