sudo: required

services:
  - docker

# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  - 7.0

# optionally specify a list of environments, for example to test different RDBMS
#env:
#  - DB=mysql
#  - DB=pgsql

before_install:
  - docker pull silintl/php7
  - sudo apt-get install php-pear
  - sudo pecl install sqlsrv-4.0.5
  - sudo pecl install pdo_sqlsrv-4.0.5
 ## INSTALLING SQLSRV
  
before_script:
  - mv application/config/database.ci.php application/config/database.php
  - cp tests/functional.suite.template.yml tests/functional.suite.yml
  - sed 's/{{test-key}}/'"$CI_TEST_KEY"'/' -i tests/functional.suite.yml
  - sudo chmod ug+x vendor/codeception/codeception/codecept
  - sudo chmod ug+x vendor/bin/codecept
  - php -S localhost:8000 > /dev/null &
  - vendor/bin/codecept build
  
script:
  - vendor/bin/codecept run functional


# configure notifications (email, IRC, campfire etc)
#notifications:
#  irc: "irc.freenode.org#travis"