# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  - 7.0

sudo: required

services:
  - docker

before_install:
  - docker pull 1and1internet/ubuntu-16-apache-php-7.0

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - sudo pecl install sqlsrv-4.0.5
  - sudo pecl install pdo_sqlsrv-4.0.5

  - echo "extension=/usr/lib/php/20151012/sqlsrv.so" >> /etc/php/7.0/apache2/php.ini
  - echo "extension=/usr/lib/php/20151012/pdo_sqlsrv.so" >> /etc/php/7.0/apache2/php.ini
  - echo "extension=/usr/lib/php/20151012/sqlsrv.so" >> /etc/php/7.0/cli/php.ini
  - echo "extension=/usr/lib/php/20151012/pdo_sqlsrv.so" >> /etc/php/7.0/cli/php.ini

  - mv application/config/database.ci.php application/config/database.php
  - cp tests/functional.suite.template.yml tests/functional.suite.yml
  - sed 's/{{test-key}}/'"$CI_TEST_KEY"'/' -i tests/functional.suite.yml
  - sudo chmod ug+x vendor/codeception/codeception/codecept
  - sudo chmod ug+x vendor/bin/codecept
  - php -S localhost:8000 > /dev/null &
  - vendor/bin/codecept build
  
script:
  - vendor/bin/codecept run functional


# configure notifications (email, IRC, campfire etc)
#notifications:
#  irc: "irc.freenode.org#travis"