SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [EASOL].[ReportLink](
	[ReportLinkId] [int] IDENTITY(1,1) NOT NULL,
	[ReportId] [int] NOT NULL,
	[URL] [nvarchar](120) NULL,
	[ColumnNo] [nvarchar](75) NULL
PRIMARY KEY CLUSTERED 
(
	[ReportLinkId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO