SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [EASOL].[ReportChart](
	[ReportChartId] [int] IDENTITY(1,1) NOT NULL,
	[ReportId] [int] NOT NULL,
	[Type] [nvarchar](75) NULL,
	[Settings] [nvarchar](max) NULL
PRIMARY KEY CLUSTERED 
(
	[ReportChartId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [EASOL].[Report] DROP COLUMN [LabelX]
GO
ALTER TABLE [EASOL].[Report] DROP COLUMN [LabelY]
GO
ALTER TABLE [EASOL].[Report] DROP COLUMN [ReportDisplayId]
GO

DROP TABLE EASOL.ReportDisplay

GO



ALTER TABLE EASOL.Report ADD DisplayType VARCHAR(20) NOT NULL DEFAULT 'table'
GO

ALTER TABLE EASOL.Report ADD Settings nvarchar(max) NULL
GO